---
- name: Install servers
  hosts: all
  roles:
    - role: geerlingguy.nginx
    - role: geerlingguy.php
      php_executable: "php"
      php_enable_php_fpm: true
      php_webserver_daemon: "nginx"
      php_fpm_listen: "/var/run/php5-fpm.sock"
      php_fpm_listen_allowed_clients: "127.0.0.1"
      php_fpm_pm_max_children: 50
      php_fpm_pm_start_servers: 5
      php_fpm_pm_min_spare_servers: 5
      php_fpm_pm_max_spare_servers: 5
    - role: geerlingguy.mysql
      mysql_root_password: toor
      mysql_databases:
        - name: some_db
    - role: domain.local
    - role: geerlingguy.git
    - role: geerlingguy.composer
  tasks:
    - name: Place nginx vhost configuration.
      template:
        src: "templates/config.conf"
        dest: "/etc/nginx/sites-enabled/vhosts.conf"
    - name: and restart nginx
      service: name=nginx state=restarted
    - name: Setup missing package
      apt: pkg=php5-mysql state=present
    - name: Fill database with tables
      mysql_db: name=some_db state=import target=/vagrant/data/db_dev_dump.sql
    - name: Install vim
      apt: name=vim state=present
    # install phpunit globally
    - name:    Download PHPUnit
      sudo:    no
      command: wget https://phar.phpunit.de/phpunit.phar
    - name:    Add executable permissions to PHPUnit
      sudo:    no
      command: chmod +x phpunit.phar
    - name:    Move PHPunit to /usr/local/bin
      sudo:    yes
      command: mv phpunit.phar /usr/local/bin/phpunit